# Generated by Django 4.2 on 2026-04-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20)),
                ('award_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='forget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='match_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.CharField(max_length=20)),
                ('ipl_no', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='match_statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=200)),
                ('team1_score', models.CharField(max_length=200)),
                ('team2_score', models.CharField(max_length=200)),
                ('captain_team1', models.CharField(max_length=200)),
                ('captain_team2', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('match_type', models.CharField(max_length=200)),
                ('no_of_overs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_details', models.CharField(max_length=20)),
                ('suspect_details', models.CharField(max_length=200)),
                ('add_players', models.CharField(max_length=200)),
                ('team_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='player_statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20)),
                ('match_id', models.CharField(max_length=50)),
                ('total_score', models.CharField(max_length=200)),
                ('no_of_catches', models.CharField(max_length=200)),
                ('no_of_wickets', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('player_type', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('debut', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('adhaar_no', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
    ]
